server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://172.20.16.1:3306/oauth
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    showSql: true
    open-in-view: false
    properties:
      javax.persistence.query.timeout: 10000
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      org.hibernate.envers.audit_table_suffix: _history
    hibernate:
      format_sql: true
      ddl-auto: none
      connection:
        charset: utf8
        useUnicode: true

#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration